---

plugins:
  - babel
  - react
  - react-hooks

env:
  node: true
  es2020: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:react/recommended'

settings:
  react:
    version: detect

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  class-methods-use-this: 0
  import/no-unresolved: 0
  no-undef: 0
  no-param-reassign: 0
  react/prop-types: 0
  react/display-name: 0
  consistent-return: 0
  no-case-declarations: 0
  no-useless-escape: 0
  react/no-children-prop: 0
  no-shadow: 0
  object-curly-newline: 0
